# Generated by Django 4.1.5 on 2023-01-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(max_length=100)),
                ('type_of_paper', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('words', models.PositiveIntegerField(default=275)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('instruction', models.FileField(upload_to='orders/')),
                ('paper_format', models.CharField(max_length=100)),
                ('socurces', models.PositiveIntegerField(default=0)),
                ('ppt', models.PositiveIntegerField(default=0)),
                ('cg', models.PositiveIntegerField(default=0, verbose_name='Charts Graphs')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='core.order')),
            ],
        ),
    ]
