# Generated by Django 4.1.5 on 2023-01-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orderdetail_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
